version: "3.9"
services:
  student-manager:
    image: student-manager
    restart: always
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      DB_HOSTNAME: mongodb
      DB_HOSTNAME: 27017
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
volumes:
  mongodb-data:
    driver: local