apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGODB_CONNECTION_STRING: mongodb://mongodb-api-4-cosmos:SbBT7lwH3OKZyO8nQgoFm75B9RfL6WN0Xu5vMjcGEzqzxB8hacDnNaV5ZoAyJtk0lLeEHBfJzOkYSxiUKHdZVw==@mongodb-api-4-cosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@mongodb-api-4-cosmos@