apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGODB_CONNECTION_STRING: mongodb://mongodb-cosmos-api:GCAOkXgmY7nWKMJZrEnEihL2f8hvMtup2vs0cJK2rgW8PjyLOF5kDh7xCGxPlETqrtmlT4HKEIX6EGp8k9BIIg==@mongodb-cosmos-api.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@mongodb-cosmos-api@