apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-manager-deployment
  labels:
    app: student-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-manager
  template:
    metadata:
      labels:
        app: student-manager
    spec:
      containers:
      - name: student-manager
        image: shoaib1999/student-manager:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.5"
        env:
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGODB_CONNECTION_STRING

---

apiVersion: v1
kind: Service
metadata:
  name: student-manager-service
spec:
  type: LoadBalancer
  selector:
    app: student-manager
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000